### ISSUE TITLE
Occasional test flake due to "Text file busy"

### ISSUE THREAD

**Issue by davidlattimore** [davidlattimore/wild#104]
I saw this yesterday once after I pushed some changes: https://github.com/davidlattimore/wild/actions/runs/10659030447/job/29540980339

then again just now on my laptop in the openSUSE docker image.

```
---- integration_test::program_name_29___rust_tls_rs__ stdout ----
Error: Failed to build program `rust-tls.rs` with linker `ld` config `global-dynamic`

Caused by:
    0: Failed to run command: OUT="/wild/wild/tests/build/rust-tls.rs-global-dynamic.ld" WILD_VALIDATE_OUTPUT="1" WILD_WRITE_LAYOUT="1" WILD_WRITE_TRACE="1" "/wild/wild/tests/build/rust-tls.global-dynamic-e9236c1fda854ff6/run-with" "/usr/bin/ld"
    1: Text file busy (os error 26)
```

I'm not sure how this can happen. It'd make sense if one thread tried to write that file concurrently with another thread executing it. However I tried stracing running the tests and it looks like the file only gets written once and executed once. Both of these should have been from the same thread so shouldn't have been concurrent.

**Comment by marxin** [comment]
How often can you reproduce the issue on your laptop? I can't to be honest.

What about using `cargo t -j1`, does the issue demonstrate? Can you attach `strace` log, please?

**Comment by davidlattimore** [comment]
I hadn't seen this happen again since I filed this issue, however I just tried running the following:

```sh
while strace --string-limit=1000 -f -ttt -o strace.log cargo test; do rm -rf wild/tests/build; done
```

It eventually failed with:

```
---- integration_test::program_name_30___rust_tls_rs__ stdout ----
Error: Failed to build program `rust-tls.rs` with linker `ld` config `initial-exec`

Caused by:
    0: Failed to run command: OUT="/home/david/work/wild/wild/tests/build/rust-tls.rs-initial-exec.ld" WILD_VALIDATE_OUTPUT="1" WILD_WRITE_LAYOUT="1" WILD_WRITE_TRACE="1" "/home/david/work/wild/wild/tests/build/rust-tls.initial-exec-8bcd8b52ca283440/run-with" "/usr/bin/ld"
    1: Text file busy (os error 26)
```

From what I've observed, the failure always seems to be in the `rust_tls_rs` test, but which config of that test fails varies. If I run just that test rather than all tests, it doesn't seem to fail - or maybe I just didn't let it run for long enough.

It's not immediately obvious which file is busy from the error. I'm starting to wonder though if it's the `run-with` file. The strace output shows it being written twice:

```
1320027:107562 1726266062.020574 openat(AT_FDCWD, "/home/david/work/wild/wild/tests/build/rust-tls.initial-exec-8bcd8b52ca283440/run-with", O_WRONLY|O_CREAT|O_TRUNC|O_CLOEXEC, 0666 <unfinished ...>
1321370:107333 1726266062.033700 openat(AT_FDCWD, "/home/david/work/wild/wild/tests/build/rust-tls.initial-exec-8bcd8b52ca283440/run-with", O_RDONLY|O_CLOEXEC <unfinished ...>
1321498:107333 1726266062.034505 openat(AT_FDCWD, "/home/david/work/wild/wild/tests/build/rust-tls.initial-exec-8bcd8b52ca283440/run-with", O_WRONLY|O_CREAT|O_TRUNC|O_CLOEXEC, 0666 <unfinished ...>
1322501:107575 1726266062.042151 execve("/home/david/work/wild/wild/tests/build/rust-tls.initial-exec-8bcd8b52ca283440/run-with", ["/home/david/work/wild/wild/tests/build/rust-tls.initial-exec-8bcd8b52ca283440/run-with", "/usr/bin/ld"], 0x71cf18799540 /* 99 vars */ <unfinished ...>
1836185:105928 1726266069.793367 write(1, "---- integration_test::program_name_30___rust_tls_rs__ stdout ----\nError: Failed to build program `rust-tls.rs` with linker `ld` config `initial-exec`\n\nCaused by:\n    0: Failed to run command: OUT=\"/home/david/work/wild/wild/tests/build/rust-tls.rs-initial-exec.ld\" WILD_VALIDATE_OUTPUT=\"1\" WILD_WRITE_LAYOUT=\"1\" WILD_WRITE_TRACE=\"1\" \"/home/david/work/wild/wild/tests/build/rust-tls.initial-exec-8bcd8b52ca283440/run-with\" \"/usr/bin/ld\"\n    1: Text file busy (os error 26)\n\n", 474) = 474
```

Although `run-with` is a bash script and I didn't think Linux locked scripts. So that's probably not it. But I suspect whatever is causing `run-with` to get written twice is also causing the problem.

The full strace output is more than 300 MB, so I can't upload it to this issue.

I also just ran with `-j1` and the problem didn't reproduce.

**Comment by davidlattimore** [comment]
The double-write of `run-with` is due to `post_process_run_script` updating the script after it has been written, so that's not it.

**Comment by davidlattimore** [comment]
Seems I was wrong about Linux not locking scripts. I just did a test on a bash script and it does lock them.

**Comment by davidlattimore** [comment]
I've extracted what I think are interesting lines from the strace:

```
107562 1726266062.020574 openat(AT_FDCWD, "/home/david/work/wild/wild/tests/build/rust-tls.initial-exec-8bcd8b52ca283440/run-with", O_WRONLY|O_CREAT|O_TRUNC|O_CLOEXEC, 0666 <unfinished ...>
107562 1726266062.020734 <... openat resumed>) = 3
107562 1726266062.021077 close(3 <unfinished ...>
107562 1726266062.021090 <... close resumed>) = 0
107333 1726266062.033700 openat(AT_FDCWD, "/home/david/work/wild/wild/tests/build/rust-tls.initial-exec-8bcd8b52ca283440/run-with", O_RDONLY|O_CLOEXEC <unfinished ...>
107333 1726266062.033782 <... openat resumed>) = 7
107333 1726266062.034264 close(7 <unfinished ...>
107333 1726266062.034343 <... close resumed>) = 0
107333 1726266062.034505 openat(AT_FDCWD, "/home/david/work/wild/wild/tests/build/rust-tls.initial-exec-8bcd8b52ca283440/run-with", O_WRONLY|O_CREAT|O_TRUNC|O_CLOEXEC, 0666 <unfinished ...>
107333 1726266062.034584 <... openat resumed>) = 6
107333 1726266062.034804 close(6 <unfinished ...>
107333 1726266062.034875 <... close resumed>) = 0
107575 1726266062.042151 execve("/home/david/work/wild/wild/tests/build/rust-tls.initial-exec-8bcd8b52ca283440/run-with", ["/home/david/work/wild/wild/tests/build/rust-tls.initial-exec-8bcd8b52ca283440/run-with", "/usr/bin/ld"], 0x71cf18799540 /* 99 vars */ <unfinished ...>
107575 1726266062.042230 <... execve resumed>) = -1 ETXTBSY (Text file busy)
```

**Comment by davidlattimore** [comment]
I've got a theory as to what might be happening. If another thread is launching a subprocess at the same time as our thread is writing the script, then when it calls `clone3`, the new subprocess will inherit the open file descriptor. The file was opened with `O_CLOEXEC`, but that means that in between when `clone3` is called and when `execve` is called, there will be an extra copy of the file descriptor. Meanwhile, our thread closes the file then immediately attempts to execute it, but it's still locked by the other process that inherited that open file descriptor and which hasn't yet been closed by a call to `execve`.

**Comment by davidlattimore** [comment]
I think the following all but confirms that this is indeed what's happening.

```
107333 1726266062.034505 openat(AT_FDCWD, "/home/david/work/wild/wild/tests/build/rust-tls.initial-exec-8bcd8b52ca283440/run-with", O_WRONLY|O_CREAT|O_TRUNC|O_CLOEXEC, 0666 <unfinished ...>
107333 1726266062.034584 <... openat resumed>) = 6
107181 1726266062.034589 clone3({flags=CLONE_VM|CLONE_VFORK, exit_signal=SIGCHLD, stack=0x71cf3dab5000, stack_size=0x9000}, 88 <unfinished ...>
107333 1726266062.034804 close(6 <unfinished ...>
107333 1726266062.034875 <... close resumed>) = 0
107574 1726266062.042085 execve("/home/david/work/wild/wild/tests/build/cpp-integration.cc-model-large.ld", ["/home/david/work/wild/wild/tests/build/cpp-integration.cc-model-large.ld"], 0x7ffefcef9c68 /* 95 vars */ <unfinished ...>
107575 1726266062.042151 execve("/home/david/work/wild/wild/tests/build/rust-tls.initial-exec-8bcd8b52ca283440/run-with", ["/home/david/work/wild/wild/tests/build/rust-tls.initial-exec-8bcd8b52ca283440/run-with", "/usr/bin/ld"], 0x71cf18799540 /* 99 vars */ <unfinished ...>
107181 1726266062.042217 <... clone3 resumed>) = 107574
107575 1726266062.042230 <... execve resumed>) = -1 ETXTBSY (Text file busy)
107574 1726266062.042277 <... execve resumed>) = 0
```

PID 107574 was created while FD 6 was open, and then has started it's `execve` call, but not completed it when PID 107575 tried to execute the script.

It's a shame that Linux doesn't have a close-on-vfork. Close-on-exec seems.... racy. The workarounds that I can this of for this are:

* Don't spawn subprocesses while you're writing files in other threads.
* Detect `ETXTBSY` and retry
* Add a sleep between creating a file and executing it (ugh)
* Instead of running the script, run bash and pass the script as an argument

**Comment by marxin** [comment]
You dug very deep :1st_place_medal: 

If I see it correctly, `integration_test`s are run by parallel threads by `rstest`. But I don't understand how can we have 2 invocations of `run-with` as the location of `run-with` is related to the input test (e.g. `wild/tests/build/rust-tls.local-exec-5f16e025f4b777db/run-with`) and I can't see a place where parallel linker invocations do happen. Do I miss something?

**Comment by davidlattimore** [comment]
The two threads don't need to be both working with the same file for this problem to occur. All that's needed is that one thread writes then executes a file, while the other thread executes anything. I wrote up a standalone demonstration of this: https://github.com/davidlattimore/linux-close-exec-race/blob/main/src/main.rs

**Comment by marxin** [comment]
Oh man! That means people must face the very same issue daily, right?

I can reproduce it very quickly as well:
```
❯ time cargo r /tmp 2
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.00s
     Running `target/debug/linux-close-exec-race /tmp 2`
/tmp/0: Text file busy (os error 26)

real	0m0.075s
user	0m0.063s
sys	0m0.024s

❯ uname -a
Linux kettlebell 6.10.9-1-default #1 SMP PREEMPT_DYNAMIC Sun Sep  8 13:43:05 UTC 2024 (5af7788) x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by davidlattimore** [comment]
I think the only reason people don't run into this issue is that writing a script then immediately executing it probably isn't a common thing to do. Or if you are doing it, you're probably not doing it from a multi-threaded program.
