### ISSUE TITLE
Expand "Linking Rust code" section

### ISSUE THREAD

**Issue by EdorianDark** [davidlattimore/wild#13]
It would be interesting to list in the section "Linking Rust code" if it also works with the [cranelift backend of rustc](https://github.com/rust-lang/rustc_codegen_cranelift?tab=readme-ov-file#user-content-fn-no-rustup-add5d39a67ad018c12cb595206385256).

**Comment by davidlattimore** [comment]
Thanks for the feedback! Wild should work with the cranelift backend - I've even got a test that verifies this. I'll have a think about how to present "what's working" in the docs.
