### ISSUE TITLE
Add support for `--no-gc-sections`

### ISSUE THREAD

**Issue by davidlattimore** [davidlattimore/wild#167]
Currently wild does `--gc-sections` by default and doesn't support not doing this.

Whether we should change the default, I'm less sure. Not GCing unused sections means that we can end up writing more stuff to the output, which slows us down.

**Comment by marxin** [comment]
Is this implemented now?

**Comment by zyxhere** [comment]
> Currently wild does `--gc-sections` by default and doesn't support not doing this.
> 
> Whether we should change the default, I'm less sure. Not GCing unused sections means that we can end up writing more stuff to the output, which slows us down.

AFAIK only rust by default enables `--gc-sections` along with LLVM's `-ffunction-sections -data-sections` at least this is what @bjorn3 said in https://users.rust-lang.org/t/how-to-use-gc-sections-link-option-to-reduce-target-binary-size/71374/5

Clang, gcc, lld, bfd and mold don't do this.

**Comment by mati865** [comment]
Yes, Rust is kinda unique by enabling it by default.
For other languages, it's common practice to enable it in the build system, in case of LLVM/Clang that is: https://github.com/llvm/llvm-project/blob/1054a6e9dee0198da0a3d234fd3254aa9e143319/llvm/cmake/modules/AddLLVM.cmake#L333

**Comment by zyxhere** [comment]
On Wed, 2025-12-03 at 13:23 -0800, Mateusz Mikuła wrote:
> mati865 left a comment (davidlattimore/wild#167)
> Yes, Rust is kinda unique by enabling it by default.
> For other languages, it's common practice to enable it in the build system, in case of LLVM/Clang that is: https://github.com/llvm/llvm-project/blob/1054a6e9dee0198da0a3d234fd3254aa9e143319/llvm/cmake/modules/AddLLVM.cmake#L333

Side note, you don't _enable_ it in build systems, you have add the
option yourself. Its not like lto or -O2,-O3 or debug symbols which the
build systems (cmake, meson) themselves implement it natively (-
DCMAKE_INTERPROCEDURAL_OPTIMIZATIONS=TRUE, -Db_lto=true for meson).

Issues could be raised by enabling it as default with C/C++ code

**Comment by davidlattimore** [comment]
If code breaks when linked with `--gc-sections` then I'd say it's pretty fragile code. So in a sense, we're helping people find what could be considered bugs in their code :)

**Comment by mati865** [comment]
> Side note, you don't _enable_ it in build systems, you have add the option yourself. Its not like lto or -O2,-O3 or debug symbols which the build systems (cmake, meson) themselves implement it natively (- DCMAKE_INTERPROCEDURAL_OPTIMIZATIONS=TRUE, -Db_lto=true for meson).

Linker options are mostly not configurable through predefined options in build systems; adding them by hand is the standard way to enable them. Moreover, the Autotools build system, if I recall correctly, doesn't provide any linker options out of the box.

Gcc and Clang don't enable `--gc-sections` by default for compatibility reasons, but for example `zig cc` does.

**Comment by zyxhere** [comment]
Since then I have found that (only) glibc breaks with --gc-sections but not going to worry too much since it breaks with pretty much anything other than GCC and the default *FLAGS.
