### ISSUE TITLE
Non-issue: Debug fuel is an ingenious technique

### ISSUE THREAD

**Issue by daniel-levin** [davidlattimore/wild#171]
Hi there! I just wanted to say how much I appreciate the cleverness and simplicity of the debug fuel technique. Turning a program into a parametric family of programs and then using binary search to find the _first_ one of interest is is ingenious.

**Comment by davidlattimore** [comment]
It is great isn't it. I can't claim any credit for it though. Rustc has [optimization fuel](https://rustc-dev-guide.rust-lang.org/mir/optimizations.html#optimization-fuel). Not sure if they were inspired in turn by something else.
