### ISSUE TITLE
Allocated too much general space in .rela.dyn. 2 of 7 entries remain unused when building C-Vise

### ISSUE THREAD

**Issue by marxin** [davidlattimore/wild#19]
Hey! I've just tried building my project [C-Vise](https://github.com/marxin/cvise) with Wild and I get:

```
❯ /usr/bin/g++  -Wall -Wextra -Werror -pedantic -Wno-unused-parameter -std=c++17 -fno-rtti -fno-strict-aliasing -fvisibility-inlines-hidden -Wno-error=mismatched-new-delete -Wno-error=maybe-uninitialized -Wno-error=class-memaccess -Wno-error=non-template-friend -g CMakeFiles/clang_delta.dir/AggregateToScalar.cpp.o CMakeFiles/clang_delta.dir/BinOpSimplification.cpp.o CMakeFiles/clang_delta.dir/CallExprToValue.cpp.o CMakeFiles/clang_delta.dir/ClangDelta.cpp.o CMakeFiles/clang_delta.dir/ClassTemplateToClass.cpp.o CMakeFiles/clang_delta.dir/ClassToStruct.cpp.o CMakeFiles/clang_delta.dir/CombineGlobalVarDecl.cpp.o CMakeFiles/clang_delta.dir/CombineLocalVarDecl.cpp.o CMakeFiles/clang_delta.dir/CopyPropagation.cpp.o CMakeFiles/clang_delta.dir/EmptyStructToInt.cpp.o CMakeFiles/clang_delta.dir/ExpressionDetector.cpp.o CMakeFiles/clang_delta.dir/InstantiateTemplateParam.cpp.o CMakeFiles/clang_delta.dir/InstantiateTemplateTypeParamToInt.cpp.o CMakeFiles/clang_delta.dir/LiftAssignmentExpr.cpp.o CMakeFiles/clang_delta.dir/LocalToGlobal.cpp.o CMakeFiles/clang_delta.dir/MoveDefinitionToDeclaration.cpp.o CMakeFiles/clang_delta.dir/MoveGlobalVar.cpp.o CMakeFiles/clang_delta.dir/ParamToGlobal.cpp.o CMakeFiles/clang_delta.dir/ParamToLocal.cpp.o CMakeFiles/clang_delta.dir/MemberToGlobal.cpp.o CMakeFiles/clang_delta.dir/ReduceArrayDim.cpp.o CMakeFiles/clang_delta.dir/ReduceArraySize.cpp.o CMakeFiles/clang_delta.dir/ReduceClassTemplateParameter.cpp.o CMakeFiles/clang_delta.dir/ReducePointerLevel.cpp.o CMakeFiles/clang_delta.dir/ReducePointerPairs.cpp.o CMakeFiles/clang_delta.dir/RemoveAddrTaken.cpp.o CMakeFiles/clang_delta.dir/RemoveArray.cpp.o CMakeFiles/clang_delta.dir/RemoveBaseClass.cpp.o CMakeFiles/clang_delta.dir/MergeBaseClass.cpp.o CMakeFiles/clang_delta.dir/RemoveCtorInitializer.cpp.o CMakeFiles/clang_delta.dir/RemoveEnumMemberValue.cpp.o CMakeFiles/clang_delta.dir/RemoveNamespace.cpp.o CMakeFiles/clang_delta.dir/RemoveNestedFunction.cpp.o CMakeFiles/clang_delta.dir/RemovePointer.cpp.o CMakeFiles/clang_delta.dir/RemoveTrivialBaseTemplate.cpp.o CMakeFiles/clang_delta.dir/RemoveTryCatch.cpp.o CMakeFiles/clang_delta.dir/RemoveUnresolvedBase.cpp.o CMakeFiles/clang_delta.dir/RemoveUnusedEnumMember.cpp.o CMakeFiles/clang_delta.dir/RemoveUnusedFunction.cpp.o CMakeFiles/clang_delta.dir/RemoveUnusedOuterClass.cpp.o CMakeFiles/clang_delta.dir/RemoveUnusedStructField.cpp.o CMakeFiles/clang_delta.dir/RemoveUnusedVar.cpp.o CMakeFiles/clang_delta.dir/RenameCXXMethod.cpp.o CMakeFiles/clang_delta.dir/RenameClass.cpp.o CMakeFiles/clang_delta.dir/RenameFun.cpp.o CMakeFiles/clang_delta.dir/RenameOperator.cpp.o CMakeFiles/clang_delta.dir/RenameParam.cpp.o CMakeFiles/clang_delta.dir/RenameVar.cpp.o CMakeFiles/clang_delta.dir/ReplaceArrayAccessWithIndex.cpp.o CMakeFiles/clang_delta.dir/ReplaceArrayIndexVar.cpp.o CMakeFiles/clang_delta.dir/ReplaceCallExpr.cpp.o CMakeFiles/clang_delta.dir/ReplaceClassWithBaseTemplateSpec.cpp.o CMakeFiles/clang_delta.dir/ReplaceDependentName.cpp.o CMakeFiles/clang_delta.dir/ReplaceDependentTypedef.cpp.o CMakeFiles/clang_delta.dir/ReplaceDerivedClass.cpp.o CMakeFiles/clang_delta.dir/ReplaceFunctionDefWithDecl.cpp.o CMakeFiles/clang_delta.dir/ReplaceOneLevelTypedefType.cpp.o CMakeFiles/clang_delta.dir/ReplaceSimpleTypedef.cpp.o CMakeFiles/clang_delta.dir/ReplaceUndefinedFunction.cpp.o CMakeFiles/clang_delta.dir/ReturnVoid.cpp.o CMakeFiles/clang_delta.dir/RewriteUtils.cpp.o CMakeFiles/clang_delta.dir/SimpleInliner.cpp.o CMakeFiles/clang_delta.dir/SimplifyCallExpr.cpp.o CMakeFiles/clang_delta.dir/SimplifyCommaExpr.cpp.o CMakeFiles/clang_delta.dir/SimplifyDependentTypedef.cpp.o CMakeFiles/clang_delta.dir/SimplifyIf.cpp.o CMakeFiles/clang_delta.dir/SimplifyNestedClass.cpp.o CMakeFiles/clang_delta.dir/SimplifyRecursiveTemplateInstantiation.cpp.o CMakeFiles/clang_delta.dir/SimplifyStruct.cpp.o CMakeFiles/clang_delta.dir/SimplifyStructUnionDecl.cpp.o CMakeFiles/clang_delta.dir/TemplateArgToInt.cpp.o CMakeFiles/clang_delta.dir/TemplateNonTypeArgToInt.cpp.o CMakeFiles/clang_delta.dir/Transformation.cpp.o CMakeFiles/clang_delta.dir/TransformationManager.cpp.o CMakeFiles/clang_delta.dir/UnifyFunctionDecl.cpp.o CMakeFiles/clang_delta.dir/UnionToStruct.cpp.o CMakeFiles/clang_delta.dir/VectorToArray.cpp.o CMakeFiles/clang_delta.dir/git_version.cpp.o -o clang_delta  -Wl,-rpath,/usr/lib64 /usr/lib64/libclang-cpp.so.18.1 /usr/lib64/libLLVM.so.18.1 -B ~/Programming/wild -Wl,--hash-style=gnu
Error: Failed copying from CMakeFiles/clang_delta.dir/TransformationManager.cpp.o (77) to output file

Caused by:
    Allocated too much general space in .rela.dyn. 2 of 7 entries remain unused.
collect2: error: ld returned 1 exit status
```

Is it something known? Would you be interested in a reduced test-case that will expose this problem?

**Comment by davidlattimore** [comment]
Thanks for the report. I have a number of similar problems. I've got a test that tries to check for such bugs, but it must be missing some combination(s). Before you go to the effort of trying to reduce a test-case, I'll have a try to see if I can extend that test to find any more such issues

**Comment by davidlattimore** [comment]
I haven't figured out what this bug might be, but I added two mechanisms that might help identify it.

The first mechanism is [this commit](https://github.com/davidlattimore/wild/commit/489f88cbbf86408115c1178c187e545ccb38940d). If that triggers, it'll start failing with a different message "Unexpected flag combination for symbol...". That will hopefully give me the information needed to figure it out.

If that doesn't trigger, then [this commit](https://github.com/davidlattimore/wild/commit/0f42d5daafc0e859ac356f7b82c00af362ea8110) adds support for printing all inputs to the allocation function for a particular input file. In your output above, the input file is file number 77, so you'd set `WILD_PRINT_ALLOCATIONS=77` when running the build and the linker would print all allocations for that file.

**Comment by marxin** [comment]
Apparently, it's not triggering the first message and thus I'm attaching the `WILD_PRINT_ALLOCATIONS` output:
[wild-cvise-output.txt](https://github.com/user-attachments/files/16310945/wild-cvise-output.txt)

Feel free to contact me for any additional information needed!

**Comment by davidlattimore** [comment]
Thanks @marxin. Good news. I've managed to reproduce the issue from a test. The problem is due to gcc's behaviour when compiling with `-pie`. It emits direct relocations to extern symbols, which means that at link time if those symbols end up coming from a shared object, the linker has to use copy relocations. IMO, copy relocations are a horrible hack that I wish didn't exist, but unfortunately they do. You can read more about them in [this excellent blog post](https://maskray.me/blog/2021-01-09-copy-relocations-canonical-plt-entries-and-protected).

**Comment by marxin** [comment]
It's good that you found the root cause! Do you have any estimation how difficult would be adding the support for that in Wild linker?

**Comment by davidlattimore** [comment]
I don't think it's too much work. I partially implemented it today - there's still a few details related to how the dynamic symbol gets emitted in the executable that I need to iron out though.

**Comment by davidlattimore** [comment]
OK, I think copy relocations are working now.

**Comment by marxin** [comment]
Thank you David!

After pulling the latest changes, I face the following issue which can be demonstrated with the following simple test case:

```
❯ printf '#include<iostream>\nint main() { std::cout << "XXX" << std::endl; return 0; }' | gcc -x c++ - -lstdc++ -B ~/Programming/wild
Error: Failed copying from /tmp/cc2xt2wm.o (4) to output file

Caused by:
    0: Failed to apply relocations in section `.text` of /tmp/cc2xt2wm.o
    1: Failed to apply relocation of type 10 to symbol `_ZSt4cout` (78 local=9) in file #4 (/tmp/cc2xt2wm.o) defined as 5736 in file #5 (/usr/lib64/gcc/x86_64-suse-linux/13/libstdc++.so) (DYNAMIC) at offset 0xa
    2: insufficient allocation to .rela.dyn (non-relative)
collect2: error: ld returned 1 exit status
```

Can you reproduce it as well?

**Comment by davidlattimore** [comment]
It doesn't reproduce on Ubuntu - tried with `gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0` and `gcc (Debian 12.2.0-14) 12.2.0` and with both, Wild is able to link the test program OK.

I just tried in a  suse docker image and was able to reproduce there. I'll see if I can figure out what's going on...

**Comment by marxin** [comment]
I bet it's somehow related to how libstdc++.so is being built. Anyway, please try installing also `gcc14-c++`, there the error message is different:

```
$ printf '#include<iostream>\nint main() { std::cout << "XXX" << std::endl; return 0; }' | gcc-14 -x c++ - -lstdc++ -B ~/Programming/wild
Error: Internal error: ExportCopyRelocation sent to non-dynamic object
collect2: error: ld returned 1 exit status
```

**Comment by davidlattimore** [comment]
Looks like one, possibly both problems are due to Wild not yet really supporting non-PIE dynamic executables. I'd considered previously if it might be possible to build a non-relocatable, dynamically linked executable, but it seemed obscure and I wasn't sure if it were even a thing. Apparently it is a thing and gcc on SUSE defaults to building non-relocatable executables even when they're dynamically linked.

**Comment by marxin** [comment]
> Looks like one, possibly both problems are due to Wild not yet really supporting non-PIE dynamic executables.

Am I correct you mean `-fno-pie` binaries that have at least one dynamically linked dependency? If so, then probably almost all binaries have a dependency to `libc.so.6`, `libgcc_s.so.1` and the `libstdc++`, right? The reason why you don't see it for Debian or Ubuntu is their GCC is configured with `--enable-default-pie`. Note, Fedora, similarly to openSUSE, **does not** use the `--enable-default-pie` option.

That said, is it really so weird use-case we're talking about?

**Comment by marxin** [comment]
This is fixed now.
