### ISSUE TITLE
`.rodata.*.str1.1` relocation is wrong

### ISSUE THREAD

**Issue by marxin** [davidlattimore/wild#24]
I noticed that while building of the `mold` linker with `wild`:

The problematic code snippet lives in `main.cc`:

```assembly
	movl	$.LC96, %esi
	call	_ZStlsISt11char_traitsIcEERSt13basic_ostreamIcT_ES5_PKc.isra.0
...
	.section	.rodata._ZN4mold3elf8elf_mainINS0_6X86_64EEEiiPPc.str1.1,"aMS",@progbits,1
.LC92:
	.string	"-run"
.LC93:
	.string	"--run"
.LC94:
	.string	"--Bstatic"
.LC95:
	.string	"--Bdynamic"
.LC96:
	.string	"-m option is missing"
.LC97:
	.string	"all"
.LC98:
	.string	"chdir failed: "
```

Reproducer branch: https://github.com/marxin/wild/tree/reproduce-rodata-issue

```
$ docker build --progress=plain -t wild-dev-opensuse . -f docker/opensuse.Dockerfile
...
#30 [builder 18/19] RUN /mold/build/mold || true
#30 0.223 mold: fatal: -m option is missing
#30 DONE 0.2s

#31 [builder 19/19] RUN /mold/build-wild/mold || true
#31 0.276 mold: fatal: chdir failed: 
#31 DONE 0.4s
```

As seen, the `mold` binary built with binutils' ld correctly prints `-m option is missing`, but the binary built with `wild` prints: `chdir failed:` (which is a string label that belongs to a different label `.LC98`).

Can you take a look, please?

**Comment by marxin** [comment]
All right, I've got a much smaller reproducer:

```shell
$ cat a.cc
#include <iostream>
using namespace std;

void bar();
void foo() {
  cout << "a" << ":" << "b" << ":" << "c" << endl;
}

int main() {
  foo();
  bar();

  return 0;
}

$ cat b.cc
#include <iostream>

using namespace std;

void bar() {
  cout << "a2" << ":" << "b2" << ":" << "c2" << endl;
}
$ g++ a.cc b.cc -O2 && ./a.out
a:b:c
a2:b2:c2
$ g++ a.cc b.cc -O2 -B ~/Programming/wild && ./a.out
a:b:c
a2bcb
```

**Comment by davidlattimore** [comment]
Thanks for the awesome bug report!

Looks like my handling of string-merge sections works where there are symbols that reference the strings, but not when the relocation is section + addend. I'll see what design I can come up with to fix it - hopefully one that doesn't kill performance.

**Comment by davidlattimore** [comment]
Both your original repro and the minimal one now produce the expected results. I ended up doing a substantial overhaul of how I was handling merge strings and am happy with the result. In the process, I managed to eliminate some heap allocations that I'd been meaning to get rid of and it looks like that resulted in a small performance boost.

**Comment by marxin** [comment]
Thank you for the quick fix :tada:

I tried to build mold now and it fails with:

```
#29 13.26 [100%] Linking CXX executable mold
#29 13.28 Error: Failed copying from CMakeFiles/mold.dir/elf/arch-riscv.cc.RV64LE.cc.o (7) to output file
#29 13.28 
#29 13.28 Caused by:
#29 13.28     0: Failed to apply relocations in section `.text` of CMakeFiles/mold.dir/elf/arch-riscv.cc.RV64LE.cc.o
#29 13.28     1: Failed to apply relocation of type 11 to symbol `.LC122` (178 local=104) in file #7 (CMakeFiles/mold.dir/elf/arch-riscv.cc.RV64LE.cc.o) (ADDRESS | CAN_BYPASS_GOT) at offset 0x87c5
#29 13.28     2: Invalid merge-string offset 18446744073709289846 in section of length 1269
#29 13.28 collect2: error: ld returned 1 exit status
```

Can you please re-run the updated branch: https://github.com/marxin/wild/tree/reproduce-rodata-issue with:

`docker build --progress=plain -t wild-dev-opensuse . -f docker/opensuse.Dockerfile` ?

**Comment by marxin** [comment]
It's something that might be related to https://github.com/rui314/mold/issues/1300, I bet it's the following thing in the assembly:

```
# /home/marxin/Programming/mold/elf/arch-riscv.cc:1085:       return (1 << 18) + get_single_letter_rank(str[1]);
	movq	%rax, %r11	# _688, _1710
	subq	$.LC122-262144, %r11	#, _1710
```

which is a symbol with big negative offset (as was discussed in the linked issue).

**Comment by davidlattimore** [comment]
So many subtle rules! I've pushed a fix. Thanks!

**Comment by marxin** [comment]
Cool, thanks for the fix! Now, I can build `mold` linker (with all targets enabled) using `wild`, and such built binary survives its test suite :tada:
