### ISSUE TITLE
Support `-X` (`--discard-locals`) option?

### ISSUE THREAD

**Issue by marxin** [davidlattimore/wild#243]
@davidlattimore can you please elaborate on the option? Is it a default behavior, or should we skip it for now (apparently it's used by default on the AArch64 Fedora system I am playing with).

**Comment by davidlattimore** [comment]
> Delete all temporary local symbols.  (These symbols start with system-specific local label prefixes, typically .L for ELF systems or L for traditional a.out systems.)

We currently discard local symbols that start with ".L", so yep, that flag does describe our current behaviour.

**Comment by marxin** [comment]
Good, included in #241.
