### ISSUE TITLE
Benchmark against mold

### ISSUE THREAD

**Issue by pinkforest** [davidlattimore/wild#3]
might be feasible to add as benchmark comparisons
https://github.com/bluewhalesystems/sold

**Comment by davidlattimore** [comment]
Shouldn't it be basically the same as mold when running on Linux?

**Comment by pinkforest** [comment]
yah it's a direct fork

**Comment by yerke** [comment]
I believe Wild only supports Linux right now. Sold is the superset of mold with the support of macOS. Since Wild doesn’t support macOS at this point, I believe there is no point in benchmarking against sold.

**Comment by marxin** [comment]
I would rename the issue to "vs mold" as sold is basically out-of-support and targeting macOS.
