### ISSUE TITLE
Add support for DWARF debug info

### ISSUE THREAD

**Issue by davidlattimore** [davidlattimore/wild#37]
I'm not 100% sure what's involved here. I gather that eh_frame info, which we already support, is somewhat related to, or a more limited form of dwarf debug info.

**Comment by davidlattimore** [comment]
> I would like to try implementing this feature ;)

Great! Thanks!

> 3\. GC of the sections should not be inhibited by a debug-info section and the corresponding relocation of a debug-info section should use a tombstone value (`0` or `1` value depending on the section name). Can you help me how to integrate that into the GC algorithm?

Do you know if we need to split the sections then GC the parts of the sections that are for functions that get GCed? I had to do that with the `.eh_frame` support and it certainly added some complexity.

If you don't need to split the sections up and you also don't want relocations in those sections to prevent other things from being GCed, then you can possibly skip reading the relocations for those sections during the layout phase. e.g `Section::create` could skip the bit where it iterates over relocations. That also assumes that the relocations don't need any allocations - i.e. that none of the relocations need to be turned into runtime relocations.

> 4\. Should we list all the supported debug-info section names (~20 sections for DWARF 4 and 5) (`OutputSectionId::regular`)? Or do we want to use a different mechanism?

If you need to refer to the sections from code - e.g. if you need special logic for a particular section, then yes. Making the sections "regular" sections means that they'll be split by alignment. I guess if a particular section needs to only ever have one particular alignment, then we could use a "generated" section - although it'd make the name "generated" slightly less appropriate.

If you don't need special logic for debug sections, or if the only special logic is that you want to not process the relocations during the layout (GC) phase, then you could add a field on `SectionDetails` - like `is_debug_info`.

**Comment by marxin** [comment]
> Do you know if we need to split the sections then GC the parts of the sections that are for functions that get GCed? I had to do that with the `.eh_frame` support and it certainly added some complexity.

No, for debug info sections, we'll only need to make the relocation resolution (with exception of `.debug_str` and `.debug_line_str` which can be candidate for string merging).

> That also assumes that the relocations don't need any allocations - i.e. that none of the relocations need to be turned into runtime relocations.

Yep, that's how I understand it as debug info is never read by a dynamic linker. It's the consumer like `gdb` or `valgrind` which loads the debug info from a (potentially different) file.

> If you don't need special logic for debug sections, or if the only special logic is that you want to not process the relocations during the layout (GC) phase, then you could add a field on `SectionDetails` - like `is_debug_info`.

Ok, I'm going to start with the suggested approach. Thanks.
