### ISSUE TITLE
Writable custom sections are put into read-only segment

### ISSUE THREAD

**Issue by davidlattimore** [davidlattimore/wild#85]
The logic got accidentally inverted in [this change](https://github.com/davidlattimore/wild/pull/79/files#diff-69bf23844df5b4ffa9cae9ff67fef7298ed201ddb8cdf8388265830b57f12629R751). This highlighted a gap in the testing because CI didn't pick it up. Fortunately due to differences on my dev machine, one test did pick it up, but I don't want to rely on that, so I'll extend a test to explicitly check for this.

**Comment by marxin** [comment]
Oh, sorry for the typo ;)
